#!/usr/bin/env python3
"""bees_config: build-time generator for a BEES program (roadmap §4.8, R0.1).

Today it has one job, from decision D30:

    bees_config.py atoms -o OUT_DIR MANIFEST...

Each MANIFEST is a `.atoms` file next to a unit: one atom spelling per line, `#` comments allowed.
The union of every manifest, in canonical (sorted) order, becomes the unit `bees_atoms.silica` in
OUT_DIR, the only unit that may write a BEAM atom literal:

    fn a_<name>() -> atom            one accessor per atom, returning the literal
    fn spelling(a: atom) -> string   the atom's spelling ("?" for an atom not in the program)
    fn index(a: atom) -> int64       canonical index (-1 for an atom not in the program)
    fn from_spelling(s: string) -> { found: boolean, value: atom }
    fn count() -> int64

The canonical index table is also written as `bees_atoms.index` (index TAB spelling), which a
language compiler reads to emit `case bees_atoms@index(a) of { 3 -> ... }` switches.

`bees_config.py check UNIT...` reports every BEAM atom literal written outside bees_atoms:
any `:name` literal that is not one of the runtime's fixed atoms (which every unit numbers
identically) and not inside a comment or string. It is a lint, not a parser: type unions such as
`:reply | :no_reply` and `child_spec` fields are Silica-level atoms the compiler resolves, so
they are on the fixed list below as well.
"""
import os
import re
import sys

# The atoms the runtime numbers identically in every unit (atom_0..atom_22 in every .sams), plus
# the atoms the compiler itself interprets in behaviour returns, child specs, supervisor messages
# and trait protocols. Any of these may be written as a literal in any unit.
FIXED_ATOMS = {
    "efficiency", "performance", "ok", "normal", "language_error", "memory_fault", "explicit",
    "unknown", "noproc", "permanent", "transient", "temporary", "one_for_one", "one_for_all",
    "rest_for_one", "insert", "lookup", "delete", "found", "not_found", "unknown_op", "plain",
    "dangerous",
    # compiler-interpreted protocol atoms
    "reply", "no_reply", "none", "worker", "supervisor", "child_started", "children", "count",
    "child_info", "error", "add_child", "count_children", "get_child", "remove_child",
    "restart_child", "terminate_child", "which_children", "less", "equal", "greater",
}

ATOM_RE = re.compile(r"(?<![A-Za-z0-9_'\"]):([A-Za-z_][A-Za-z0-9_]*)")


def read_manifests(paths):
    atoms = set()
    for p in paths:
        with open(p) as fh:
            for line in fh:
                line = line.split("#", 1)[0].strip()
                if line:
                    atoms.add(line)
    return sorted(atoms)


def accessor_name(spelling):
    """a_<spelling> when the spelling is an identifier; otherwise hex-escape the odd characters."""
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", spelling):
        return "a_" + spelling
    return "a_x" + "".join(c if re.fullmatch(r"[A-Za-z0-9]", c) else "_%02x" % ord(c) for c in spelling)


def silica_string(spelling):
    return '"' + spelling.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_atoms(out_dir, manifests):
    atoms = read_manifests(manifests)
    bad = [a for a in atoms if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", a)]
    if bad:
        # Silica's atom literal syntax is :identifier; quoted atoms need a spelling table entry
        # only, which is not generated yet (contract item 1 will say how such atoms are written).
        print("bees_config: atoms that are not identifiers are not supported yet: " + ", ".join(bad), file=sys.stderr)
        return 1
    lines = ["// Generated by tools/bees_config.py (D30). Do not edit; do not write BEAM atom literals elsewhere.",
             "module bees_atoms;", ""]
    for a in atoms:
        lines.append(f"export {accessor_name(a)}/0;")
    lines += ["export spelling/1;", "export index/1;", "export from_spelling/1;", "export count/0;", ""]
    for a in atoms:
        lines += [f"fn {accessor_name(a)}() -> atom {{ :{a} }}"]
    lines.append("")
    lines.append("fn spelling(a: atom) -> string {")
    lines.append("    case a of {")
    for a in atoms:
        lines.append(f"        :{a} -> {silica_string(a)};")
    lines.append('        _: atom -> "?"')
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("fn index(a: atom) -> int64 {")
    lines.append("    case a of {")
    for i, a in enumerate(atoms):
        lines.append(f"        :{a} -> {i};")
    lines.append("        _: atom -> -1")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("fn from_spelling(s: string) -> { found: boolean, value: atom } {")
    # A chain of string comparisons; a compiler-generated jump table is not available for strings.
    body = "{ found: false, value: :unknown }"
    for a in reversed(atoms):
        body = f"case s == {silica_string(a)} of {{ true -> {{ found: true, value: :{a} }}; false -> {body} }}"
    lines.append("    " + body)
    lines.append("}")
    lines.append("")
    lines.append(f"fn count() -> int64 {{ {len(atoms)} }}")
    lines.append("")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "bees_atoms.silica"), "w") as out:
        out.write("\n".join(lines))
    with open(os.path.join(out_dir, "bees_atoms.index"), "w") as out:
        for i, a in enumerate(atoms):
            out.write(f"{i}\t{a}\n")
    return 0


def strip_comments_and_strings(src):
    src = re.sub(r"//[^\n]*", "", src)
    src = re.sub(r'"(?:\\.|[^"\\])*"', '""', src)
    src = re.sub(r"'(?:\\.|[^'\\])'", "''", src)
    return src


def check(units):
    rc = 0
    for u in units:
        if os.path.basename(u) == "bees_atoms.silica":
            continue
        with open(u) as fh:
            src = strip_comments_and_strings(fh.read())
        for lineno, line in enumerate(src.split("\n"), 1):
            for m in ATOM_RE.finditer(line):
                if m.group(1) not in FIXED_ATOMS:
                    print(f"{u}:{lineno}: BEAM atom literal :{m.group(1)} outside bees_atoms (D30)")
                    rc = 1
    return rc


def main(argv):
    if len(argv) >= 4 and argv[1] == "atoms" and argv[2] == "-o":
        return gen_atoms(argv[3], argv[4:])
    if len(argv) >= 3 and argv[1] == "check":
        return check(argv[2:])
    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
