#!/usr/bin/env python3
"""Generate src/shim/bees_term.silica (and bees_recv.silica) from templates.

Silica has no type names, so the term cell type is spelled in full in every signature. The
templates use these placeholders:

    $T    the cell type      (int64, int64, float64, atom, actor_ref, ref?(L, normal, rec), ref?(L, normal, rec))
    $R    a reference to a cell         ref(L, normal, $T)
    $O    an optional reference         ref?(L, normal, rec)
    $H    the heap record: region plus the last cell made   { r: region(L, normal), c: $O }
    $C    a cell wrapper record         { c: $O }

Run from the repository root: python3 tools/gen_bees_term.py
"""
import os

T = "(int64, int64, float64, atom, actor_ref, ref?(L, normal, rec), ref?(L, normal, rec))"
R = f"ref(L, normal, {T})"
O = "ref?(L, normal, rec)"
H = f"{{ r: region(L, normal), c: {O} }}"
C = f"{{ c: {O} }}"

BEES_TERM = """module bees_term;
// GENERATED by tools/gen_bees_term.py; edit the template there.
//
// bees_term v0 (spike S9; contract item 1 draft). A term is a cell in a region:
//   (tag, n, f, a, p, h, t)
//   tag  0 nil  1 int(n)  2 float(f)  3 mk_atom(a)  4 pid(p)  5 mk_cons(h=head, t=tail)
//        6 tuple(n=arity, h=element list)  7 binary(n=byte count, h=list of int cells 0..255)
//        8 fun(n=module index, h=(fn index, env list) as a cons)
// Every atom in a term comes from bees_atoms (D30); this unit writes none.
// Constructors take and return the heap record { r, c } (SD-20: a (region, ref) tuple return
// crashes on actor threads) and put the new cell in c. Every region that holds terms is
// region(L, normal) (SD-6). Optional references are written ref?(L, normal, rec) (SD-4) and are
// bound only through records (SD-5).

export mk_nil/1;
export mk_int/2;
export mk_float/2;
export mk_atom/2;
export mk_pid/2;
export mk_cons/3;
export mk_tuple/3;
export tag/1;
export int_of/1;
export float_of/1;
export atom_of/1;
export pid_of/1;
export hd_of/1;
export tl_of/1;
export arity/1;
export list_len/1;
export nth/2;
export copy/2;
export eq/2;
export is_none/1;
export wrap/1;
export heap_of/1;
export wrap_ref/1;

fn some(c: $R) -> $O { c }
// The public widening of a cell reference to an optional one (SD-5).
fn wrap_ref(c: $R) -> $O { c }
fn wrap(c: $O) -> $C { { c: c } }
// The heap record for a region with no cell yet (a record literal with :none needs this return type).
fn heap_of(r: region(L, normal)) -> $H { { r: r, c: :none } }
fn is_none(c: $O) -> boolean { case c of { :none -> true; _: $R -> false } }

fn mk_nil(h: $H) -> $H {
    sequence proc[mem(normal), concurrency]
        c: $R <- alloc_rec(h.r, (0, 0, 0.0, :ok, self(), :none, :none))
    produces pure { r: h.r, c: some(c) } end
}
fn mk_int(h: $H, n: int64) -> $H {
    sequence proc[mem(normal), concurrency]
        c: $R <- alloc_rec(h.r, (1, n, 0.0, :ok, self(), :none, :none))
    produces pure { r: h.r, c: some(c) } end
}
fn mk_float(h: $H, f: float64) -> $H {
    sequence proc[mem(normal), concurrency]
        c: $R <- alloc_rec(h.r, (2, 0, f, :ok, self(), :none, :none))
    produces pure { r: h.r, c: some(c) } end
}
fn mk_atom(h: $H, a: atom) -> $H {
    sequence proc[mem(normal), concurrency]
        c: $R <- alloc_rec(h.r, (3, 0, 0.0, a, self(), :none, :none))
    produces pure { r: h.r, c: some(c) } end
}
fn mk_pid(h: $H, p: actor_ref) -> $H {
    sequence proc[mem(normal)]
        c: $R <- alloc_rec(h.r, (4, 0, 0.0, :ok, p, :none, :none))
    produces pure { r: h.r, c: some(c) } end
}
fn mk_cons(h: $H, hd: $O, tl: $O) -> $H {
    sequence proc[mem(normal), concurrency]
        c: $R <- alloc_rec(h.r, (5, 0, 0.0, :ok, self(), hd, tl))
    produces pure { r: h.r, c: some(c) } end
}
// A tuple of arity n over a list of its elements (built with cons, nil-terminated).
fn mk_tuple(h: $H, n: int64, elements: $O) -> $H {
    sequence proc[mem(normal), concurrency]
        c: $R <- alloc_rec(h.r, (6, n, 0.0, :ok, self(), elements, :none))
    produces pure { r: h.r, c: some(c) } end
}

fn read(c: $R) -> $T {
    sequence proc[mem(normal)]
        node: $T <- read_ref(c)
    produces pure node end
}

fn tag(c: $O) -> int64 {
    case c of {
        :none -> 0 - 1;
        x: $R -> {
            (tg: int64, _: int64, _: float64, _: atom, _: actor_ref, _: $O, _: $O) <- read(x);
            tg
        }
    }
}
fn int_of(c: $O) -> int64 {
    case c of {
        :none -> 0;
        x: $R -> {
            (_: int64, n: int64, _: float64, _: atom, _: actor_ref, _: $O, _: $O) <- read(x);
            n
        }
    }
}
// A float64-returning function must not destructure the cell (SD-14 class: the emitter uses D0
// as the base register), so the slot is fetched through a record.
fn float_slot(x: $R) -> { f: float64 } {
    sequence proc[mem(normal)]
        node: $T <- read_ref(x);
        (_: int64, _: int64, f: float64, _: atom, _: actor_ref, _: $O, _: $O) <- node
    produces pure { f: f } end
}
fn fzero() -> float64 { 0.0 }
fn float_of(c: $O) -> float64 {
    case c of {
        :none -> fzero();
        x: $R -> fget(float_slot(x))
    }
}
fn fget(s: { f: float64 }) -> float64 { s.f }
fn atom_of(c: $O) -> atom {
    case c of {
        :none -> :unknown;
        x: $R -> {
            (_: int64, _: int64, _: float64, a: atom, _: actor_ref, _: $O, _: $O) <- read(x);
            a
        }
    }
}
fn pid_of(c: $O) -> actor_ref {
    sequence proc[concurrency]
        me: actor_ref <- self();
        p: actor_ref <- case c of {
            :none -> me;
            x: $R -> {
                (_: int64, _: int64, _: float64, _: atom, q: actor_ref, _: $O, _: $O) <- read(x);
                q
            }
        }
    produces pure p end
}
fn hd_of(c: $O) -> $C {
    case c of {
        :none -> { c: :none };
        x: $R -> {
            (_: int64, _: int64, _: float64, _: atom, _: actor_ref, hd: $O, _: $O) <- read(x);
            { c: hd }
        }
    }
}
fn tl_of(c: $O) -> $C {
    case c of {
        :none -> { c: :none };
        x: $R -> {
            (_: int64, _: int64, _: float64, _: atom, _: actor_ref, _: $O, tl: $O) <- read(x);
            { c: tl }
        }
    }
}
fn arity(c: $O) -> int64 { int_of(c) }

// Length of a cons list (nil-terminated); a non-list ends the count.
fn list_len(c: $O) -> int64 {
    case tag(c) == 5 of {
        true -> {
            t: $C <- tl_of(c);
            1 + list_len(t.c)
        };
        false -> 0
    }
}
// The i-th element (0-based) of a cons list, or none.
fn nth(c: $O, i: int64) -> $C {
    case tag(c) == 5 of {
        true -> case i == 0 of {
            true -> hd_of(c);
            false -> {
                t: $C <- tl_of(c);
                nth(t.c, i - 1)
            }
        };
        false -> { c: :none }
    }
}

// Deep copy of a term from any region into the heap h (evacuation, roadmap §4.2).
fn copy(h: $H, c: $O) -> $H {
    case c of {
        :none -> { r: h.r, c: :none };
        x: $R -> {
            (tg: int64, n: int64, f: float64, a: atom, p: actor_ref, hd: $O, tl: $O) <- read(x);
            case tg of {
                5 -> {
                    h1: $H <- copy(h, hd);
                    h2: $H <- copy(h1, tl);
                    mk_cons(h2, h1.c, h2.c)
                };
                6 -> {
                    h1: $H <- copy(h, hd);
                    mk_tuple(h1, n, h1.c)
                };
                2 -> mk_float(h, f);
                3 -> mk_atom(h, a);
                4 -> mk_pid(h, p);
                1 -> mk_int(h, n);
                _: int64 -> mk_nil(h)
            }
        }
    }
}

// Structural equality (=:= for the v0 types; floats compare exactly).
fn eq(a: $O, b: $O) -> boolean {
    case tag(a) == tag(b) of {
        false -> false;
        true -> case tag(a) of {
            0 -> true;
            1 -> int_of(a) == int_of(b);
            2 -> feq(float_of(a), float_of(b));
            3 -> atom_of(a) == atom_of(b);
            4 -> same_pid(pid_of(a), pid_of(b));
            5 -> {
                ha: $C <- hd_of(a);
                hb: $C <- hd_of(b);
                ta: $C <- tl_of(a);
                tb: $C <- tl_of(b);
                eq(ha.c, hb.c) and eq(ta.c, tb.c)
            };
            6 -> {
                ha: $C <- hd_of(a);
                hb: $C <- hd_of(b);
                arity(a) == arity(b) and eq(ha.c, hb.c)
            };
            _: int64 -> false
        }
    }
}
fn feq(x: float64, y: float64) -> boolean { x == y }
// Pid equality waits on S-26: actor_ref_equal is specified (2026-09-15) but not in the fixed
// point (it links as an undefined symbol), and the comparison operators do not apply to
// references. Until then two pids are never equal (recorded in the S9 note).
fn same_pid(x: actor_ref, y: actor_ref) -> boolean { false }
"""

BEES_RECV = """module bees_recv;
// GENERATED by tools/gen_bees_term.py; edit the template there.
//
// The save queue for reshaped `receive` (D1, spike S9). A process that is waiting in a receive
// keeps the messages that did not match in a cons list in its own heap, oldest first. When it
// enters a receive it first takes from the queue; a message that arrives and does not match is
// appended. Matching is a predicate the compiler emits for the receive's patterns.

use bees_term;

export append/3;
export take/3;

// Append the term m (already copied into the heap) at the end of the queue q.
fn append(h: $H, q: $O, m: $O) -> $H {
    case bees_term@tag(q) == 5 of {
        false -> {
            h1: $H <- bees_term@mk_nil(h);
            bees_term@mk_cons(h1, m, h1.c)
        };
        true -> {
            hd: $C <- bees_term@hd_of(q);
            tl: $C <- bees_term@tl_of(q);
            h1: $H <- append(h, tl.c, m);
            bees_term@mk_cons(h1, hd.c, h1.c)
        }
    }
}

// Take the first queued message satisfying the predicate. Returns the heap, the queue without
// that message, and the message (or none). found is false when nothing matched.
fn take(h: $H, q: $O, matches: fn($O) -> boolean) -> { r: region(L, normal), rest: $O, taken: $O, found: boolean } {
    case bees_term@tag(q) == 5 of {
        false -> { r: h.r, rest: q, taken: :none, found: false };
        true -> {
            hd: $C <- bees_term@hd_of(q);
            tl: $C <- bees_term@tl_of(q);
            case matches(hd.c) of {
                true -> { r: h.r, rest: tl.c, taken: hd.c, found: true };
                false -> {
                    inner: { r: region(L, normal), rest: $O, taken: $O, found: boolean } <- take(h, tl.c, matches);
                    h2: $H <- bees_term@mk_cons(bees_term@heap_of(inner.r), hd.c, inner.rest);
                    { r: h2.r, rest: h2.c, taken: inner.taken, found: inner.found }
                }
            }
        }
    }
}
"""


def expand(s):
    return s.replace("$T", T).replace("$R", R).replace("$O", O).replace("$H", H).replace("$C", C)


if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for name, src in (("bees_term.silica", BEES_TERM), ("bees_recv.silica", BEES_RECV)):
        with open(os.path.join(root, "src", "shim", name), "w") as f:
            f.write(expand(src))
    print("generated bees_term.silica, bees_recv.silica")
